### PR TITLE
Addon.xml fixes and summary addition for lang "de"

### PR DESCRIPTION
**Pull request by DaVukovic**
If you ever might think of submitting that plugin to the kodi repo, those changes might be required. 

Also probably add a license. Which one is up to you. Common GPLv2. 

Unfortunately I don´t know Italian language. So I can´t add anything for that ;)

### CODE REVIEW

**Comment by lusum** [comment]
This is already the original license file, from the original author. The addon is licensed gplv2

see  https://github.com/lusum/ampache-xbmc-plugin/blob/master/LICENSE

**Comment by DaVukovic** [comment]
Cool, fine then. My thought was to mention the license at the addon.xml as well. Lke:

`<license>whatever license in use</license>`

Just a thought ;)

**Comment by lusum** [comment]
I will merge both the pull requests, they don't touch the codebase, so no need for testing.

**Comment by lusum** [comment]
No problem, and thanks!

**Pull request merged**
